[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.40"
rocket = { version = "0.5.0-rc.3", default-features = false }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.blast]
path = "../blast"
