[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.40"
rocket = { version = "0.5.0-rc.3", default-features = false }

[dependencies.blast-macros]
path = "../blast-macros"

[dependencies.blast-interface]
path = "../blast-interface"